[package]
name = "rust-pubsub"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
log = "0.4.27"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
